### ISSUE TITLE
Feature Request:  mass change privacy on past posts

### ISSUE THREAD

**Issue by k1n6b0b** [chander/social-network-cleaner#7]
Love the concept of this and i've been looking for something for a while!  My request would be to have the option to optionally mass limit old posts by group.  For instance I'd like to create a group called "old posts blocked" and add everyone post-college to that group, then limit privacy on everything (exactly like your delete function) before a certain date.

I looked at the code and each component having it's own xpaths specific to delete - i dont think i would have the skills to fork and make the changes myself, tho if I could I would be glad to help extend functionality.

**Comment by chander** [comment]
I don't think this is an easy change.  Right now things are really geared towards deleting/removing.  One would need to figure out the xpaths to change all the current delete stuff to "change visibility" (so a different group has access.)  Probably best to try and fork things instead.

You might have more luck asking FB to implement such a feature - I'm sure it's not hard, given they already have functionality to limit past posts....
